### ISSUE TITLE
the 'dmos_realigned.mat' of LIVE database

### ISSUE THREAD

**Issue by yinglili666** [SSL92/hyperIQA#11]
I want to train the model on LIVE database, but there is an error about 'dmos_realigned.mat'.  The code is here 
''dmos = scipy.io.loadmat(os.path.join(root, 'dmos_realigned.mat'))
labels = dmos['dmos_new'].astype(np.float32)''

Is it correct for me to replace  'dmos_realigned.mat' with ‘dmos.mat' and 'dmos_new' with 'dmos'(using the mat file in live database) , or have you processed the data in any other way?

Thank you

**Comment by SSL92** [comment]
So what is the error reported?

**Comment by yinglili666** [comment]
> So what is the error reported?

when I used the code you published, there is an error that No such file or directory about 'dmos_realigned.mat'. Then I replace  'dmos_realigned.mat' with ‘dmos.mat' , the 'KeyError: 'dmos_new'' is occurred.

**Comment by SSL92** [comment]
Seems you're using a Release 1 version of LIVE dataset, see [http://live.ece.utexas.edu/research/Quality/subjective.htm](url) and get a Release 2 version, the problem should be solved.

**Comment by yinglili666** [comment]
> Seems you're using a Release 1 version of LIVE dataset, see [http://live.ece.utexas.edu/research/Quality/subjective.htm](url) and get a Release 2 version, the problem should be solved.

I think I know the reason. I used the release2 but I don't download the realigned subjective quality data. thank you!

**Comment by SSL92** [comment]
Cool
