### ISSUE TITLE
regarding the logistic regression before plcc

### ISSUE THREAD

**Issue by seyeeet** [SSL92/hyperIQA#18]
in the paper mentioned that:
```
Before calculating PLCC, logistic regression is first
applied to remove nonlinear rating caused by human visual
observation, as suggested in the report from Video Quality
Expert Group (VQEG) [11].
```
can you please share the logistic regression function that is used?

**Comment by lllllllllllll-llll** [comment]
Hello, you can use the matlab code for logistic regression.
https://github.com/lllllllllllll-llll/SROCC_PLCC_calculate

**Comment by seyeeet** [comment]
@lllllllllllll-llll thanks, I was hoping to get a python version :p

**Comment by lllllllllllll-llll** [comment]
> @lllllllllllll-llll thanks, I was hoping to get a python version :p
Usually, when you do the single database evaluation test (e.g. train on LIVE, test on LIVE), you do not need to do the logistic regression for PLCC. The logistic regression is only applied when you do the cross test evaluation (e.g. train on LIVE, test on CSIQ), which you can use the matlab code.
