### ISSUE TITLE
Problems of Implementation Details. Some difference?

### ISSUE THREAD

**Issue by lllllllllllll-llll** [SSL92/hyperIQA#4]
The data augmentation part of this code is different from the implementation details.  It says: "we randomly sample and horizontally flipping 25 patches with size 224x224 pixels ... ", and "During testing stage, 25 patches with 224x224 pixels from test image are randomly sampled and their corresponding ... ", but I can not find the part about randomly crop 25 patches, can you point out where this part is? What I find just the normal torchvision.transforms.Compose from data_loader.py instead of randomly crop 25 patches.

**Comment by SSL92** [comment]
> The data augmentation part of this code is different from the implementation details. It says: "we randomly sample and horizontally flipping 25 patches with size 224x224 pixels ... ", and "During testing stage, 25 patches with 224x224 pixels from test image are randomly sampled and their corresponding ... ", but I can not find the part about randomly crop 25 patches, can you point out where this part is? What I find just the normal torchvision.transforms.Compose from data_loader.py instead of randomly crop 25 patches.

Data augmentation is conducted in folders.py, see line 50, 98 for LIVE and LIVEC data, for instance.

**Comment by lllllllllllll-llll** [comment]
roger that
